#Source file

SRC = test_server.cpp service.pb.cpp
HDR = tcp_connection.h handler_base.h
#Object file
OBJ = $(SRC:.cpp=.o)

#Output execution file
PROGRAM = test_server
PROGRAM_EXT = bin

#Compiler
CC = g++

#Protobuf
PROTOBUF = /localview/vrgm63/tmp/protobuf-2.3.0/src
#Boost
BOOST = /localview/vrgm63/tmp/boost_1_44_0
#Include
INCLUDE = -I/usr/include/ncurses -I/usr/include/ -I$(BOOST) -I$(PROTOBUF)
#Linker Parameter
LINKPARAM = -L$(BOOST)/stage/lib -L$(PROTOBUF)/.libs -lpthread -lncurses \
	-lboost_thread -lboost_system -lprotobuf
#Options for development
CFLAGS = -ansi -g -Wall
#Options for release
#CFLAGS = -ansi -O -Wall

all: $(PROGRAM).$(PROGRAM_EXT)

$(PROGRAM).$(PROGRAM_EXT): $(OBJ)
	$(CC) -o $(PROGRAM).$(PROGRAM_EXT) $(LINKPARAM) $(OBJ)  

.SUFFIXES = .cpp

.cpp.o: 
	$(CC) $(INCLUDE) $(CFLAGS) -c $<

clean:
	rm *.o

